### ISSUE TITLE
[BUG] Detected that custom integration 'brematic' calls async_write_ha_state from a thread

### ISSUE THREAD

**Issue by TheZoker** [tefinger/hass-brematic#14]
**Describe the bug**

This is the log:
```
EG Jalousie Rechts: Error executing script. Unexpected error for call_service at pos 1: Detected that custom integration 'brematic' calls async_write_ha_state from a thread at custom_components/brematic/switch.py, line 242: self.async_write_ha_state(). Please report it to the author of the 'brematic' custom integration.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 501, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 736, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2705, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2746, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1680, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/brematic/switch.py", line 242, in turn_on
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'brematic' calls async_write_ha_state from a thread at custom_components/brematic/switch.py, line 242: self.async_write_ha_state(). Please report it to the author of the 'brematic' custom integration.
```

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Home Assistant:**
 - Home Assistant Version: 2024.5
 - Brematic Component Version: [e.g. 0.1.1]

**Additional context**

**Comment by johndoe0815** [comment]
When will a new release be issued to close that bug? At the moment my switches always throw this error. 
`Fehler beim Aufrufen des Diensts light/turn_on. Detected that custom integration 'brematic' calls async_write_ha_state from a thread at custom_components/brematic/switch.py, line 242: self.async_write_ha_state(). Please report it to the author of the 'brematic' custom integration.` (when I want to turn off, it refers to line 251).
For some reason sometimes they still turn on/off, but mostly not.

**Comment by TheZoker** [comment]
@johndoe0815 If you want to fix this yourself in the meantime, you can change the files according to the PR #15 
If you need help doing that, let me know!

**Comment by johndoe0815** [comment]
> @johndoe0815 If you want to fix this yourself in the meantime, you can change the files according to the PR #15 If you need help doing that, let me know!

I actually managed to do so and it works again as before, thanks!
